[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://coral-app-ycosl.ondigitalocean.app/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

