name: izonedevs
services:
  - name: backend
    github:
      repo: takudzwachitsungo/izone-platform-backend
      branch: main
      deploy_on_push: true
    source_dir: /backend
    run_command: uvicorn main:app --host 0.0.0.0 --port 8080
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    routes:
      - path: /api
    envs:
      - key: DATABASE_URL
        value: sqlite:///./izonedevs.db
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: DEBUG
        value: "false"
        
  - name: frontend
    github:
      repo: takudzwachitsungo/izone-platform-backend
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: npm install && npm run build
    run_command: npm run preview -- --host 0.0.0.0 --port 8080
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    routes:
      - path: /
    envs:
      - key: VITE_API_URL
        value: ${APP_URL}/api