name: izonedevs
region: nyc

# Static sites (defined first)
static_sites:
  # Frontend - must be first to be default, catches all non-API routes
  - name: frontend
    source_dir: frontend
    output_dir: dist
    build_command: npm install && npm run build
    index_document: index.html
    error_document: index.html
    routes:
      - path: /
    envs:
      - key: VITE_API_URL
        value: https://coral-app-ycosl.ondigitalocean.app/api

  # Uploads storage
  - name: uploads
    source_dir: backend/uploads
    routes:
      - path: /uploads

services:
  # Backend API - specific routes only
  - name: backend
    source_dir: backend
    environment_slug: python
    build_command: pip install -r requirements.txt
    run_command: uvicorn main:app --host 0.0.0.0 --port 8080
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
      - path: /docs
      - path: /redoc
      - path: /openapi.json
    envs:
      - key: DATABASE_URL
        value: sqlite:///./izonedevs.db
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: DEBUG
        value: "false"
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: izonemakers@gmail.com
      - key: SMTP_PASSWORD
        scope: RUN_TIME
        type: SECRET