name: izonedevs
region: nyc

services:
  # Single service - backend serves both API and pre-built frontend
  - name: app
    source_dir: .
    environment_slug: python
    build_command: cd backend && pip install -r requirements.txt
    run_command: cd backend && uvicorn main:app --host 0.0.0.0 --port 8080
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DATABASE_URL
        value: sqlite:///./izonedevs.db
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: DEBUG
        value: "false"
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: izonemakers@gmail.com
      - key: SMTP_PASSWORD
        scope: RUN_TIME
        type: SECRET